# Generated by Django 4.1.7 on 2023-04-07 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DemoApplication', '0002_student'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='student',
            table='STUDENT',
        ),
    ]
