# Generated by Django 4.1.7 on 2023-04-07 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DemoApplication', '0003_alter_student_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='locations',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
